-- Enforcement subsystem expansion for Sabi API.

USE sabi_db;

CREATE TABLE IF NOT EXISTS staff_roles (
    id             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    teacher_id     INT UNSIGNED NOT NULL,
    role           ENUM('principal','vice_principal','hr','admin','hod','class_teacher','year_tutor') NOT NULL,
    subject_scope  VARCHAR(100) NULL,
    class_scope    VARCHAR(50) NULL,
    level_scope    VARCHAR(100) NULL,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    assigned_by    VARCHAR(150) NULL,
    notes          TEXT NULL,
    assigned_on    DATE NOT NULL,
    created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    UNIQUE KEY uq_teacher_role_scope (teacher_id, role, subject_scope, class_scope, level_scope),
    INDEX idx_role (role, is_active),
    INDEX idx_subject (subject_scope, role)
) COMMENT 'Designates leadership and scoped routing roles for OpenClaw workflows.';

CREATE TABLE IF NOT EXISTS teacher_assignments (
    id                    INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    teacher_id            INT UNSIGNED NOT NULL,
    term_id               INT UNSIGNED NOT NULL,
    enterprise_class_id   VARCHAR(20) NOT NULL,
    enterprise_subject_id VARCHAR(28) NOT NULL,
    class_name            VARCHAR(100) NOT NULL,
    subject_name          VARCHAR(100) NOT NULL,
    created_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    FOREIGN KEY (term_id) REFERENCES academic_terms(id),
    UNIQUE KEY uq_assignment (teacher_id, term_id, enterprise_class_id, enterprise_subject_id)
) COMMENT 'Subject-class combinations per teacher per term.';

CREATE TABLE IF NOT EXISTS enforcement_rules (
    id                     INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    rule_key               VARCHAR(80) NOT NULL UNIQUE,
    rule_name              VARCHAR(200) NOT NULL,
    is_active              BOOLEAN NOT NULL DEFAULT TRUE,
    reminder_days_before   INT UNSIGNED NOT NULL DEFAULT 1,
    escalate_l1_days_after INT UNSIGNED NOT NULL DEFAULT 1,
    escalate_l2_days_after INT UNSIGNED NOT NULL DEFAULT 2,
    reminder_message       TEXT NULL,
    due_today_message      TEXT NULL,
    defaulted_message      TEXT NULL,
    l1_report_template     TEXT NULL,
    l2_query_template      TEXT NULL,
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT 'Configurable thresholds and message templates for each enforcement rule.';

CREATE TABLE IF NOT EXISTS enforcement_log (
    id                 INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    rule_id            INT UNSIGNED NOT NULL,
    teacher_id         INT UNSIGNED NOT NULL,
    term_id            INT UNSIGNED NOT NULL,
    reference          VARCHAR(300) NOT NULL,
    stage              ENUM('reminder','due_today','defaulted','escalated_l1','escalated_l2','resolved') NOT NULL,
    reminder_sent_at   DATETIME NULL,
    due_today_sent_at  DATETIME NULL,
    defaulted_sent_at  DATETIME NULL,
    escalated_l1_at    DATETIME NULL,
    escalated_l2_at    DATETIME NULL,
    resolved_at        DATETIME NULL,
    query_draft        TEXT NULL,
    query_confirmed_by VARCHAR(150) NULL,
    query_served_at    DATETIME NULL,
    created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (rule_id) REFERENCES enforcement_rules(id),
    FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    FOREIGN KEY (term_id) REFERENCES academic_terms(id),
    INDEX idx_enforcement_lookup (teacher_id, term_id, stage)
) COMMENT 'Every violation, reminder, escalation, and resolution event.';

CREATE TABLE IF NOT EXISTS staff_escalations (
    id                 INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    enforcement_log_id INT UNSIGNED NOT NULL,
    teacher_id         INT UNSIGNED NOT NULL,
    escalation_stage   VARCHAR(40) NOT NULL,
    recipient_role     VARCHAR(40) NOT NULL,
    message            TEXT NOT NULL,
    created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (enforcement_log_id) REFERENCES enforcement_log(id),
    FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    INDEX idx_staff_escalations (teacher_id, recipient_role, created_at)
) COMMENT 'Admin/principal escalation notices generated by the enforcement flow.';

CREATE TABLE IF NOT EXISTS attendance_confirmations (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    teacher_id          INT UNSIGNED NOT NULL,
    term_id             INT UNSIGNED NOT NULL,
    enterprise_class_id VARCHAR(20) NOT NULL,
    confirm_date        DATE NOT NULL,
    session             ENUM('morning','noon') NOT NULL,
    confirmed_at        DATETIME NOT NULL,
    FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    FOREIGN KEY (term_id) REFERENCES academic_terms(id),
    UNIQUE KEY uq_attendance_confirmation (teacher_id, enterprise_class_id, confirm_date, session)
) COMMENT 'Daily register confirmation via Telegram or WhatsApp.';

CREATE TABLE IF NOT EXISTS scheme_of_work (
    id             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    teacher_id     INT UNSIGNED NOT NULL,
    term_id        INT UNSIGNED NOT NULL,
    subject        VARCHAR(100) NOT NULL,
    class_name     VARCHAR(50) NOT NULL,
    total_topics   TINYINT UNSIGNED NOT NULL,
    topics_covered TINYINT UNSIGNED NOT NULL DEFAULT 0,
    last_updated   DATETIME NULL,
    FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    FOREIGN KEY (term_id) REFERENCES academic_terms(id),
    UNIQUE KEY uq_scheme_progress (teacher_id, term_id, subject, class_name)
) COMMENT 'Scheme completion percentage per teacher per class per term.';

CREATE TABLE IF NOT EXISTS homework_logs (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    teacher_id  INT UNSIGNED NOT NULL,
    term_id     INT UNSIGNED NOT NULL,
    class_name  VARCHAR(50) NOT NULL,
    subject     VARCHAR(100) NOT NULL,
    week_number TINYINT UNSIGNED NOT NULL,
    given_on    DATE NOT NULL,
    due_date    DATE NOT NULL,
    description TEXT NULL,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    FOREIGN KEY (term_id) REFERENCES academic_terms(id),
    UNIQUE KEY uq_homework_week (teacher_id, term_id, class_name, subject, week_number)
) COMMENT 'Weekly homework issued per teacher per class and subject.';

INSERT INTO enforcement_rules (
    rule_key, rule_name, is_active, reminder_days_before, escalate_l1_days_after, escalate_l2_days_after,
    reminder_message, due_today_message, defaulted_message, l1_report_template, l2_query_template
) VALUES
('lesson_plan_submission', 'Lesson Plan Submission', TRUE, 1, 2, 2,
 'Hello {teacher_name}. Your {reference} is due {deadline}. Please submit before the cutoff.',
 'Warning: {teacher_name}, your {reference} is due today ({deadline}). This is your final reminder.',
 'Default notice: {teacher_name}, you missed {reference}. This matter will be escalated.',
 'Principal alert: {teacher_name} is in default for {reference}.',
 'Formal query draft for {teacher_name}: failure to comply with lesson plan submission for {reference}.'),
('scheme_of_work', 'Scheme of Work Completion', TRUE, 3, 3, 2,
 'Hello {teacher_name}. Please update your scheme of work progress for {reference} before {deadline}.',
 'Warning: {teacher_name}, your scheme progress for {reference} is due for review today.',
 'Default notice: {teacher_name}, your scheme progress remains below policy for {reference}.',
 'Principal alert: {teacher_name} is below required scheme completion for {reference}.',
 'Formal query draft for {teacher_name}: failure to maintain required scheme completion for {reference}.'),
('result_upload', 'Result Upload Compliance', TRUE, 1, 2, 2,
 'Hello {teacher_name}. Please upload pending results for {reference} before {deadline}.',
 'Warning: {teacher_name}, result upload for {reference} is due today.',
 'Default notice: {teacher_name}, results for {reference} remain outstanding.',
 'Principal alert: {teacher_name} has outstanding result uploads for {reference}.',
 'Formal query draft for {teacher_name}: failure to upload results for {reference}.'),
('attendance_logging', 'Attendance Logging', TRUE, 0, 1, 1,
 'Hello {teacher_name}. Please complete {reference} by {deadline}.',
 'Warning: {teacher_name}, {reference} is due today.',
 'Default notice: {teacher_name}, {reference} was not completed on time.',
 'Principal alert: {teacher_name} defaulted on {reference}.',
 'Formal query draft for {teacher_name}: failure to complete {reference}.'),
('pd_target', 'Professional Development Target', TRUE, 7, 7, 7,
 'Hello {teacher_name}. Your PD progress ({reference}) is below target. Please update before {deadline}.',
 'Warning: {teacher_name}, your PD target remains below policy today.',
 'Default notice: {teacher_name}, your PD target remains unmet.',
 'Principal alert: {teacher_name} has not met the PD target ({reference}).',
 'Formal query draft for {teacher_name}: failure to meet PD target for the term.'),
('teacher_lateness', 'Teacher Lateness', TRUE, 0, 1, 2,
 'Hello {teacher_name}. This is a reminder regarding punctuality: {reference}.',
 'Warning: {teacher_name}, your punctuality record breaches policy today: {reference}.',
 'Default notice: {teacher_name}, repeated lateness has triggered enforcement.',
 'Principal alert: {teacher_name} has repeated lateness ({reference}).',
 'Formal query draft for {teacher_name}: repeated lateness ({reference}).'),
('absenteeism', 'Teacher Absenteeism', TRUE, 0, 0, 1,
 'Hello {teacher_name}. Please regularise your attendance record for {reference}.',
 'Warning: {teacher_name}, your attendance issue ({reference}) requires immediate explanation.',
 'Default notice: {teacher_name}, unapproved absenteeism has been recorded.',
 'Principal alert: {teacher_name} has unapproved absenteeism ({reference}).',
 'Formal query draft for {teacher_name}: unapproved absenteeism ({reference}).'),
('homework_giving', 'Homework Giving', TRUE, 1, 2, 2,
 'Hello {teacher_name}. Please log homework for {reference} before {deadline}.',
 'Warning: {teacher_name}, homework log for {reference} is due today.',
 'Default notice: {teacher_name}, homework for {reference} has not been logged.',
 'Principal alert: {teacher_name} has not logged homework for {reference}.',
 'Formal query draft for {teacher_name}: failure to log homework for {reference}.')
ON DUPLICATE KEY UPDATE
    rule_name = VALUES(rule_name),
    is_active = VALUES(is_active),
    reminder_days_before = VALUES(reminder_days_before),
    escalate_l1_days_after = VALUES(escalate_l1_days_after),
    escalate_l2_days_after = VALUES(escalate_l2_days_after),
    reminder_message = VALUES(reminder_message),
    due_today_message = VALUES(due_today_message),
    defaulted_message = VALUES(defaulted_message),
    l1_report_template = VALUES(l1_report_template),
    l2_query_template = VALUES(l2_query_template);
